package tests;

public class seleniumNotes {

    /*
    TestBase
Utility class
There is before and after methods in this class
Our test base is abstract so we just extend and use the methods
This kind of utility classes makes the actual test classes short and clean
Iframes
Iframe is used to add page within a page, maps, videos, scrollbars,…
Driver must switch to iframe first to see the elements in the frame
driver.switchTo().frame(“by using id/name, index, or web-element”);-> get in
driver.switchTo().parentFrame() or defaultContent()
Multiple windows
The multiple windows may open when there is a link that opens in a new TAB or WINDOWS
We use windowHandle to get the current window id, windowHandles to get all open windows ids
We use set of list to get all window ids and switch to the desired window using loop and if condition
Alerts
Alerts are generated by javascript alerts. For example when clicking a button, we can see informative alerts
When there is an alert, we must handle it first to continue the test execution.
We cannot inspect alerts, but we can handle alerts by switching them first
driver.switchTo().alert().  —-accept(), dissmiss(), getText(), and sendKeys()——
     */
}
